### ISSUE TITLE
Backported data is intermittently inconsistent due to updating in-place

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#257] opened 2022-06-28 12:35 UTC
## Problem

When a backported dataset is updated, it overwrites the old object in S3. This invalidates all previous walden versions, which no longer point to data with a valid checksum.

## Proposed solution

Overwrite the walden record, but not the S3 object. Instead, treat S3 as an append-only store and use the has in the S3 path.

## Example

```
977. walden://backport/latest/dataset_5085_google_mobility_trends__2020_values...
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/bin/etl", line 5, in <module>
    main()
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 93, in main
    run_dag(
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 159, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 166, in timed_run
    f()
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 159, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/steps/__init__.py", line 440, in run
    self._walden_dataset.ensure_downloaded(quiet=True)
  File "/Users/lars/Documents/owid/etl/vendor/walden/owid/walden/catalog.py", line 196, in ensure_downloaded
    files.download(url, filename, expected_md5=self.md5, quiet=quiet)
  File "/Users/lars/Documents/owid/etl/vendor/walden/owid/walden/files.py", line 90, in download
    raise ChecksumDoesNotMatch(f"for file downloaded from {url}")
owid.walden.files.ChecksumDoesNotMatch: for file downloaded from https://walden.nyc3.digitaloceanspaces.com/backport/latest/dataset_5085_google_mobility_trends__2020_values.feather
```

**Comment by Marigold** [comment] 2022-06-28 15:15
The file got updated at 2:01pm which was 30 minutes before we discovered the bug. Is it possible that we didn't have up to date walden catalog? Running `etl dataset_5085 --backport` on a fresh ETL builds it correctly.

As for the other error
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://walden.nyc3.digitaloceanspaces.com/backport/latest/dataset_1002_incidence_of_managerial_or_professional_jobs_and_collective_bargaining_by_gender__blau_and_kahn__2017_config.json
```
I was able to replicate it with `etl dataset_1002 --backport`. The problem is that deleted / archived datasets were not removed from walden index. There's a [PR with a fix](https://github.com/owid/etl/pull/219) if you have some spare time. In the meantime I'll remove those problematic datasets from walden index.

**Comment by larsyencken** [comment] 2022-07-25 17:41
Had another transient error like this now:

```
File "/Users/lars/Documents/owid/etl/vendor/walden/owid/walden/files.py", line 90, in download
    raise ChecksumDoesNotMatch(
owid.walden.files.ChecksumDoesNotMatch: for file downloaded from https://walden.nyc3.digitaloceanspaces.com/backport/latest/dataset_5205_covid_2019__hospital__and__icu_config.json:
        walden index checksum = 0311fc0c8bc869fec8993374a3389fd9
        downloaded checksum = 2fff8f6ce31279f069126fee41191568
```

10 mins later it seemed to clear itself after a `git pull`.

I wonder if we could avoid them by swapping `/latest/` in the object store path with `/<hash>/` when storing them to S3. That way it works both before and after a backport, and this transient issue should disappear.

@Marigold Thoughts?

**Comment by Marigold** [comment] 2022-07-26 06:38
Haven't seen this one yet, but you're right that this could happen, especially with covid updates.

Using `hash` in path is a neat idea, I'll check how hard would it be and whether there might be any side effects.

**Comment by larsyencken** [comment] 2022-07-27 14:53
Got this again now, it's very often for me. I'm going to try patching it

```
(.venv) lars@juniper owid/etl (master) » etl --backport --private
Detecting which steps need rebuilding...
Running 787 steps:
1. walden-private://backport/latest/dataset_5220_covid_19__johns_hopkins_university_values...
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/bin/etl", line 5, in <module>
    main_cli()
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 77, in main_cli
    return main(
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 116, in main
    run_dag(
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 200, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 207, in timed_run
    f()
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 200, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/steps/__init__.py", line 437, in run
    self._walden_dataset.ensure_downloaded(quiet=True)
  File "/Users/lars/Documents/owid/etl/vendor/walden/owid/walden/catalog.py", line 201, in ensure_downloaded
    owid_cache.download(url, filename, expected_md5=self.md5, quiet=quiet)
  File "/Users/lars/Documents/owid/etl/vendor/walden/owid/walden/owid_cache.py", line 100, in download
    raise ChecksumDoesNotMatch(f"for file downloaded from {s3_url}")
owid.walden.files.ChecksumDoesNotMatch: for file downloaded from https://walden.nyc3.digitaloceanspaces.com/backport/latest/dataset_5220_covid_19__johns_hopkins_university_values.feather
```

**Comment by Marigold** [comment] 2022-07-28 10:26
Thanks @larsyencken, don't be afraid to cut deep if you need to. You'd have to be pulling latest walden changes before backporting and it's even possible it could fail if some updates were pushed to walden in the meantime.

**Comment by larsyencken** [comment] 2022-08-01 21:14
Another transient error like this, this time on prod.

```
owid.walden.files.ChecksumDoesNotMatch: for file downloaded from https://walden.nyc3.digitaloceanspaces.com/backport/latest/dataset_4864_share_of_one_person_households__owid_based_on_un_and_other_sources_values.feather
```

**Comment by larsyencken** [comment] 2022-08-03 12:49
Mojmir and I agreed to delay backport-related changes until we're clearer on architecture options, so that we know the work will be used.

**Comment by larsyencken** [comment] 2022-09-24 11:42
Bumping it because it's still an issue with reliably building the ETL.

**Comment by larsyencken** [comment] 2022-09-24 20:35
Another case breaking prod:

```
owid.walden.files.ChecksumDoesNotMatch: for file downloaded from https://walden.nyc3.digitaloceanspaces.com/backport/latest/dataset_5712_food_security__suite_of_food_security_indicators__fao__2022_05_17_config.json:
	walden index checksum = c65b2a99e22983a7b94768367239f6c7
	downloaded checksum = de14cfd4751dece384e393a0d1cadc8c
```

After looking into more of these cases, I can't work out why they are happening, but they are not temporary fast-track issues.

In situations like these, an existing walden cache has the file with the right checksum, but it cannot be downloaded anymore from the original source -- no fresh ETL clone on a fresh machine will build properly, not when backports are included.

Bumping the priority once more.

**Comment by Marigold** [comment] 2022-09-26 08:42
@larsyencken I've been able to replicate this for dataset 5669 which breaks ETL build. It looks like the file in S3 got updated 5 days ago, but walden index didn't get updated and is 10 days old. I'm still searching through logs what could have happened, I'd guess it wasn't able to push to walden for some reason (someone else pushing to walden at the same time?).

Using hashes as versions should fix the build. We'd still use outdated backported dataset though (I'll check whether it can self-repair on next backport run)

**Comment by Marigold** [comment] 2022-09-26 09:10
Oh shit, it was me. I was updating broken UN SDG in production, I ran backport locally and forgot to push changes to walden... Using the hashes should prevent these kinds of bugs in the future (or at least raise a different more useful error).

**Comment by larsyencken** [comment] 2022-12-05 08:34
Keeping this one open, it's something @Marigold aims to fix with Snapshots.

**Comment by Marigold** [comment] 2022-12-05 08:37
@larsyencken I already have a [PR for that](https://github.com/owid/etl/pull/641). If you are not busy and can take a look I'd really appreciate it! (Pablo has been pretty busy lately).

**Comment by Marigold** [comment] 2023-01-03 09:59
Fixed with Snapshots.

**Closed by Marigold** 2023-01-03 09:59 UTC
Labels: bug, pinned, priority 2 - important
