### ISSUE TITLE
Unable to re-run grapher step because dataset already exists

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#487] opened 2022-09-20 07:18 UTC
I have changed the metadata of a dataset, and, when trying to run the grapher step again (to update the metadata in grapher), etl fails. The error seems to be that the dataset already exists.
This can be replicated by re-running the `grapher/energy/2022-08-03/electricity_mix` step.

**Comment by Marigold** [comment] 2022-09-20 09:12
@pabloarosado I can't replicate it unfortunately, could you please post here the full traceback and ideally outputs of the following SQLs?

```sql
select id, name, shortName, version from datasets where name = 'Electricity mix (BP & Ember, 2022)';
```

```sql
select id, name, shortName from variables where datasetId = [id from previous SQL];
```

**Comment by pabloarosado** [comment] 2022-09-20 09:24
Thanks @Marigold, maybe it's an issue with my local grapher.
**Traceback**:
```
3. grapher://grapher/energy/2022-08-03/electricity_mix...
2022-09-20 09:17.16 [info     ] upsert_dataset.verify_namespace namespace=energy
2022-09-20 09:17.16 [info     ] upsert_dataset.upsert_dataset.start short_name=electricity_mix
2022-09-20 09:17:16,846 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'Electricity mix (BP & Ember, 2022)-energy' for key 'datasets.datasets_name_namespace_d3d60d22_uniq'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/bin/etl", line 5, in <module>
    main_cli()
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/prosado/Documents/owid/repos/etl/etl/command.py", line 119, in main_cli
    main(**kwargs)  # type: ignore
  File "/Users/prosado/Documents/owid/repos/etl/etl/command.py", line 147, in main
    run_dag(
  File "/Users/prosado/Documents/owid/repos/etl/etl/command.py", line 236, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/Users/prosado/Documents/owid/repos/etl/etl/command.py", line 243, in timed_run
    f()
  File "/Users/prosado/Documents/owid/repos/etl/etl/command.py", line 236, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/Users/prosado/Documents/owid/repos/etl/etl/steps/__init__.py", line 503, in run
    dataset_upsert_results = upsert_dataset(
  File "/Users/prosado/Documents/owid/repos/etl/etl/grapher_import.py", line 93, in upsert_dataset
    ds = gm.Dataset.from_dataset_metadata(
  File "/Users/prosado/Documents/owid/repos/etl/etl/grapher_model.py", line 350, in upsert
    return session.exec(q).one()
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlmodel/orm/session.py", line 60, in exec
    results = super().execute(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 316, in orm_pre_session_exec
    session._autoflush()
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2257, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb.IntegrityError) (1062, "Duplicate entry 'Electricity mix (BP & Ember, 2022)-energy' for key 'datasets.datasets_name_namespace_d3d60d22_uniq'")
[SQL: INSERT INTO datasets (name, `shortName`, version, namespace, description, `createdAt`, `updatedAt`, `isPrivate`, `createdByUserId`, `metadataEditedAt`, `metadataEditedByUserId`, `dataEditedAt`, `dataEditedByUserId`, `nonRedistributable`, `isArchived`, `sourceChecksum`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('Electricity mix (BP & Ember, 2022)', 'electricity_mix', '2022-08-03', 'energy', '', datetime.datetime(2022, 9, 20, 7, 17, 16, 824851), datetime.datetime(2022, 9, 20, 7, 17, 16, 824851), 0, 58, datetime.datetime(2022, 9, 20, 7, 17, 16, 824856), 58, datetime.datetime(2022, 9, 20, 7, 17, 16, 824857), 58, 0, 0, None)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Query**:
```
select id, name, shortName, version from datasets where name = 'Electricity mix (BP & Ember, 2022)';
```
**Result**:
```
5678	Electricity mix (BP & Ember, 2022)	electricity_mix__energy_2022_08_03	2022-08-03
```

**Query**:
```
select id, name, shortName from variables where datasetId = 5678;
```
Result:
```
471881	Electricity from bioenergy (TWh)	bioenergy_generation__twh
471882	Bioenergy (% electricity)	bioenergy_share_of_electricity__pct
471883	Carbon intensity of electricity (gCO2/kWh)	co2_intensity__gco2_kwh
471884	Electricity from coal (TWh)	coal_generation__twh
471885	Coal (% electricity)	coal_share_of_electricity__pct
471886	Electricity from fossil fuels (TWh)	fossil_generation__twh
471887	Fossil fuels (% electricity)	fossil_share_of_electricity__pct
471888	Electricity from gas (TWh)	gas_generation__twh
471889	Gas (% electricity)	gas_share_of_electricity__pct
471890	Electricity from hydro (TWh)	hydro_generation__twh
471891	Hydro (% electricity)	hydro_share_of_electricity__pct
471892	Low-carbon electricity (TWh)	low_carbon_generation__twh
471893	Low-carbon electricity (% electricity)	low_carbon_share_of_electricity__pct
471894	Net electricity imports as a share of demand (%)	net_imports_share_of_demand__pct
471895	Electricity from nuclear (TWh)	nuclear_generation__twh
471896	Nuclear (% electricity)	nuclear_share_of_electricity__pct
471897	Electricity from oil (TWh)	oil_generation__twh
471898	Oil (% electricity)	oil_share_of_electricity__pct
471899	Other renewables excluding bioenergy (TWh)	other_renewables_excluding_bioenergy_generation__twh
471900	Other renewables excluding bioenergy (% electricity)	other_renewables_excluding_bioenergy_share_of_electricity__pct
471901	Other renewables including bioenergy (TWh)	other_renewables_including_bioenergy_generation__twh
471902	Other renewables including bioenergy (% electricity)	other_renewables_including_bioenergy_share_of_electricity__pct
471903	Bioenergy electricity per capita (kWh)	per_capita_bioenergy_generation__kwh
471904	Coal electricity per capita (kWh)	per_capita_coal_generation__kwh
471905	Fossil fuel electricity per capita (kWh)	per_capita_fossil_generation__kwh
471906	Gas electricity per capita (kWh)	per_capita_gas_generation__kwh
471907	Hydro electricity per capita (kWh)	per_capita_hydro_generation__kwh
471908	Low-carbon electricity per capita (kWh)	per_capita_low_carbon_generation__kwh
471909	Nuclear electricity per capita (kWh)	per_capita_nuclear_generation__kwh
471910	Oil electricity per capita (kWh)	per_capita_oil_generation__kwh
471911	Other renewable electricity excluding bioenergy per capita (kWh)	per_capita_other_renewables_excluding_bioenergy_generation__kwh
471912	Other renewable electricity including bioenergy per capita (kWh)	per_capita_other_renewables_including_bioenergy_generation__kwh
471913	Renewable electricity per capita (kWh)	per_capita_renewable_generation__kwh
471914	Solar electricity per capita (kWh)	per_capita_solar_generation__kwh
471915	Per capita electricity (kWh)	per_capita_total_generation__kwh
471916	Wind electricity per capita (kWh)	per_capita_wind_generation__kwh
471917	Electricity from primary energy consumption (twh) (TWh)	primary_energy_consumption__twh
471918	Electricity from renewables (TWh)	renewable_generation__twh
471919	Renewables (% electricity)	renewable_share_of_electricity__pct
471920	Electricity from solar (TWh)	solar_generation__twh
471921	Solar (% electricity)	solar_share_of_electricity__pct
471922	Electricity demand (TWh)	total_demand__twh
471923	Electricity as share of primary energy (%)	total_electricity_share_of_primary_energy__pct
471924	Emissions (MtCO2)	total_emissions__mtco2
471925	Electricity generation (TWh)	total_generation__twh
471926	Net imports (TWh)	total_net_imports__twh
471927	Electricity from wind (TWh)	wind_generation__twh
471928	Wind (% electricity)	wind_share_of_electricity__pct
```

**Comment by pabloarosado** [comment] 2022-09-20 09:26
I suppose I need to update my local grapher database, given that `electricity_mix__energy_2022_08_03` is still the old short name. So would updating the grapher container solve the issue?

**Comment by larsyencken** [comment] 2022-09-20 10:57
This seems very similar to #486 , where we wanted to update a variable but it failed when one was already in place.

**Comment by larsyencken** [comment] 2022-09-20 11:00
I can reproduce it locally as well.

**Comment by Marigold** [comment] 2022-09-20 13:45
@pabloarosado yes, that's most likely the issue. You need to apply [the migration in grapher](https://owid.slack.com/archives/C0193RW5E2J/p1663333758695649) or as you say, update the grapher container.

@larsyencken is your dataset using old format of short names with versions too or can you reproduce it after the migration?

**Comment by lucasrodes** [comment] 2022-09-20 14:33
Probably duplicate of https://github.com/owid/etl/issues/486

**Comment by pabloarosado** [comment] 2022-09-20 14:48
Thanks @Marigold, I've updated grapher and re-run the same grapher step, and now I get a slightly different error. Now it's not complaining about the dataset being duplicated, but the first variable being duplicated:
```
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb.IntegrityError) (1062, "Duplicate entry 'Electricity from bioenergy (TWh)-5678' for key 'variables.variables_name_fk_dst_id_f7453c33_uniq'")
[SQL: INSERT INTO variables (`datasetId`, name, `shortName`, description, unit, `createdAt`, `updatedAt`, coverage, timespan, `sourceId`, display, `columnOrder`, code, `shortUnit`, `originalMetadata`, `grapherConfig`, `catalogPath`, dimensions) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (5678, 'Electricity from bioenergy (TWh)', 'bioenergy_generation_twh', None, 'terawatt-hours', datetime.datetime(2022, 9, 20, 14, 40, 38, 660429), datetime.datetime(2022, 9, 20, 14, 40, 38, 660431), '', '1990-2021', 27045, '{"name": "Bioenergy", "shortUnit": "TWh", "unit": "terawatt-hours"}', 0, None, 'TWh', None, None, 'grapher/energy/2022-08-03/electricity_mix/electricity_mix', None)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```
I've also tried pulling the latest grapher and running `yarn runDbMigrations`, but I still get the same issue.

**Comment by larsyencken** [comment] 2022-09-20 15:16
Post grapher migration I also get the same issue as @pabloarosado above.

**Comment by Marigold** [comment] 2022-09-20 20:14
Thank you both, that SQL output helped a lot. It happens only for this dataset and the reason is that we use **double underscore** in column names, e.g. `bioenergy_generation__twh`. This double underscore then [gets converted into a single underscore](https://github.com/owid/etl/blob/3865f87ebc58366f7e2fc4ac8f17f66f9ec7f88d/etl/grapher_helpers.py#L217) before inserting to DB...

Which is wrong behaviour in my opinion. It is still using the old slugify function instead of underscore function that keeps double underscores. I've [created a PR](https://github.com/owid/etl/pull/491) that doesn't modify column name and matches on both single and double underscores when doing upserts. That should get rid of this error and correctly update short names on grapher upserts.

**Comment by pabloarosado** [comment] 2022-09-21 07:46
[I'm thinking](https://owid.slack.com/archives/C0193RW5E2J/p1663745593524109) that maybe we should simply use single underscores everywhere. But if you disagree, feel free to ignore it.

**Closed** 2022-09-21 10:55 UTC
Labels: bug, help wanted, priority 1 - essential
