### ISSUE TITLE
Add a maintainer field to the metadata

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2414] opened 2024-03-14 10:30 UTC
## Problem

When we use the admin, it shows when indicators were last changed but not who changed them, which makes it more annoying to ask questions or follow up on changes to our data.

<img width="1727" alt="Screenshot 2024-03-14 at 10 31 19" src="https://github.com/owid/etl/assets/36012/b2cc3bc3-2302-43ca-8b9c-7e3b0549cdc0">

## Idea

We could add a `maintainer` field at the dataset level, and all edits could be attributed to them when present.

## Alternatives

- Some kind of tricky mapping of git usernames to our OWID internal accounts

## Technical notes

- If we had this link, it would also be useful for a ton of downstream tools and applications where knowing who is associated with a dataset is helpful

**Comment by Marigold** [comment] 2024-05-15 04:34
We discussed this at the offsite and agreed that it'd be a very nice feature (we should implement it as part of other metadata changes).

**Comment by pabloarosado** [comment] 2024-06-04 11:21
I'm closing this issue, as it seems to be a duplicate of https://github.com/owid/etl/issues/2465

**Closed by pabloarosado** 2024-06-04 11:21 UTC
Labels: priority 3 - nice to have
